export * from "../components/Navbar/style";
export * from "../components/Sidebar/style";
export * from "../components/Hero/style";
export * from "../components/Footer/style";
export * from "../components/Button/style";
export * from "../components/InfoSection/style";
export * from "../components/Services/style";
export * from "../components/Projects/style";
export * from "../components/Singup/style";
